export type BloatwareEntry = {
  pattern: string;
  title: string;
  description: string;
  group: "consumer" | "office" | "gaming" | "communication" | "media" | "system" | "oem" | "other";
  recommended?: boolean;
  warning?: string;
  /** Icon identifier, resolved by `iconUrl()` in `apps/catalog.ts`. */
  icon?: string;
};

export const BLOATWARE: BloatwareEntry[] = [
  // Consumer / Bing apps
  { pattern: "Microsoft.BingNews", title: "Bing News", description: "MSN News reader", group: "consumer", recommended: true, icon: "microsoft-bing" },
  { pattern: "Microsoft.BingWeather", title: "Bing Weather", description: "Weather app", group: "consumer", recommended: true, icon: "microsoft-bing" },
  { pattern: "Microsoft.BingSearch", title: "Bing Search", description: "Bing web search integrated into Windows Search", group: "consumer", recommended: true, icon: "microsoft-bing" },
  { pattern: "Microsoft.BingFinance", title: "Bing Finance", description: "Finance news and tracking via Bing (discontinued)", group: "consumer", recommended: true, icon: "microsoft-bing" },
  { pattern: "Microsoft.BingSports", title: "Bing Sports", description: "Sports news and scores via Bing (discontinued)", group: "consumer", recommended: true, icon: "microsoft-bing" },
  { pattern: "Microsoft.BingFoodAndDrink", title: "Bing Food & Drink", description: "Recipes and food news via Bing (discontinued)", group: "consumer", recommended: true, icon: "microsoft-bing" },
  { pattern: "Microsoft.BingHealthAndFitness", title: "Bing Health & Fitness", description: "Health and fitness tracking via Bing (discontinued)", group: "consumer", recommended: true, icon: "microsoft-bing" },
  { pattern: "Microsoft.BingTranslator", title: "Bing Translator", description: "Translation service via Bing", group: "consumer", recommended: true, icon: "microsoft-bing" },
  { pattern: "Microsoft.BingTravel", title: "Bing Travel", description: "Travel planning via Bing (discontinued)", group: "consumer", recommended: true, icon: "microsoft-bing" },
  { pattern: "Microsoft.News", title: "Microsoft News", description: "News aggregator (Microsoft Start)", group: "consumer", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.GetHelp", title: "Get Help", description: "Microsoft support chat", group: "consumer", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.Getstarted", title: "Get Started", description: "Tips & tricks app", group: "consumer", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.WindowsAlarms", title: "Alarms & Clock", description: "Alarms / timer app", group: "consumer", icon: "microsoft-windows" },
  { pattern: "Microsoft.WindowsMaps", title: "Maps", description: "Maps app", group: "consumer", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.MixedReality.Portal", title: "Mixed Reality Portal", description: "Windows MR portal", group: "consumer", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.OneConnect", title: "Mobile Plans", description: "Microsoft OneConnect / mobile operator portal", group: "consumer", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.3DBuilder", title: "3D Builder", description: "Basic 3D modeling software", group: "consumer", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.Microsoft3DViewer", title: "3D Viewer", description: "Viewer for 3D models", group: "consumer", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.Print3D", title: "Print 3D", description: "3D printing preparation software", group: "consumer", recommended: true, icon: "microsoft-windows" },

  // Office & productivity (Microsoft + UWP)
  { pattern: "Microsoft.MicrosoftOfficeHub", title: "Office Hub", description: "Office promo entry in the Start menu", group: "office", recommended: true, icon: "microsoft-office" },
  { pattern: "Microsoft.MicrosoftStickyNotes", title: "Sticky Notes", description: "Sticky Notes app", group: "office", icon: "microsoft-windows" },
  { pattern: "Microsoft.PowerAutomateDesktop", title: "Power Automate", description: "Workflow automation tool", group: "office", icon: "microsoft-power-automate" },
  { pattern: "Microsoft.Todos", title: "Microsoft To Do", description: "Task list app", group: "office", icon: "microsoft-to-do" },
  { pattern: "Microsoft.Office.OneNote", title: "OneNote", description: "OneNote (Store version)", group: "office", icon: "microsoft-onenote" },
  { pattern: "Microsoft.Office.Sway", title: "Sway", description: "Presentation and storytelling app", group: "office", recommended: true, icon: "microsoft-office" },
  { pattern: "Microsoft.MicrosoftJournal", title: "Microsoft Journal", description: "Digital note-taking app for pen input", group: "office", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.MicrosoftPowerBIForWindows", title: "Power BI", description: "Business analytics client", group: "office", recommended: true, icon: "microsoft-power-bi" },
  { pattern: "Microsoft.M365Companions", title: "Microsoft 365 Companions", description: "M365 Calendar/Files/People mini-apps", group: "office", warning: "May be re-deployed by your M365 admin.", icon: "microsoft-365" },
  { pattern: "Microsoft.Whiteboard", title: "Microsoft Whiteboard", description: "Digital collaborative whiteboard", group: "office", icon: "microsoft-windows" },
  { pattern: "DrawboardPDF", title: "Drawboard PDF", description: "PDF viewing and annotation app for pen input", group: "office", recommended: true, icon: "favicon:drawboard.com" },
  { pattern: "Wunderlist", title: "Wunderlist", description: "To-do list app (acquired by Microsoft → To Do)", group: "office", recommended: true, icon: "favicon:wunderlist.com" },
  { pattern: "OneCalendar", title: "One Calendar", description: "Calendar aggregation app", group: "office", recommended: true, icon: "favicon:onecalendar.de" },

  // Gaming & Xbox
  { pattern: "Microsoft.MicrosoftSolitaireCollection", title: "Solitaire Collection", description: "Ad-supported Solitaire bundle", group: "gaming", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.Xbox.TCUI", title: "Xbox TCUI", description: "Xbox UI runtime", group: "gaming", warning: "Some games depend on this.", icon: "xbox" },
  { pattern: "Microsoft.XboxApp", title: "Xbox App (Old)", description: "Xbox console companion (discontinued)", group: "gaming", recommended: true, icon: "xbox" },
  { pattern: "Microsoft.XboxGameOverlay", title: "Xbox Game Overlay", description: "Xbox in-game overlay", group: "gaming", recommended: true, icon: "xbox" },
  { pattern: "Microsoft.XboxGamingOverlay", title: "Xbox Game Bar", description: "Game Bar overlay", group: "gaming", recommended: true, icon: "xbox" },
  { pattern: "Microsoft.XboxIdentityProvider", title: "Xbox Identity Provider", description: "Xbox sign-in component", group: "gaming", warning: "Required for games using Xbox Live.", icon: "xbox" },
  { pattern: "Microsoft.XboxSpeechToTextOverlay", title: "Xbox Speech to Text", description: "Xbox voice output", group: "gaming", recommended: true, icon: "xbox" },
  { pattern: "Microsoft.GamingApp", title: "Xbox / Gaming App", description: "PC Game Pass app", group: "gaming", icon: "xbox-game-pass" },
  { pattern: "Microsoft.Edge.GameAssist", title: "Edge Game Assist", description: "Edge gaming overlay", group: "gaming", recommended: true, icon: "microsoft-edge" },
  // Bundled third-party games
  { pattern: "*HiddenCity*", title: "Hidden City", description: "Hidden-object adventure game", group: "gaming", recommended: true, icon: "favicon:g5e.com" },
  { pattern: "*CandyCrush*", title: "Candy Crush (all variants)", description: "King's Candy Crush bundle", group: "gaming", recommended: true, icon: "favicon:king.com" },
  { pattern: "king.com.BubbleWitch3Saga", title: "Bubble Witch 3", description: "Puzzle game from King", group: "gaming", recommended: true, icon: "favicon:king.com" },
  { pattern: "Asphalt8Airborne", title: "Asphalt 8 Airborne", description: "Racing game from Gameloft", group: "gaming", recommended: true, icon: "favicon:gameloft.com" },
  { pattern: "CaesarsSlotsFreeCasino", title: "Caesars Slots", description: "Casino slot machine game", group: "gaming", recommended: true, icon: "favicon:caesars.com" },
  { pattern: "COOKINGFEVER", title: "Cooking Fever", description: "Restaurant simulation game", group: "gaming", recommended: true, icon: "favicon:nordcurrent.com" },
  { pattern: "DisneyMagicKingdoms", title: "Disney Magic Kingdoms", description: "Disney theme park building game", group: "gaming", recommended: true, icon: "disney-plus" },
  { pattern: "FarmVille2CountryEscape", title: "FarmVille 2: Country Escape", description: "Farming simulation game", group: "gaming", recommended: true, icon: "favicon:zynga.com" },
  { pattern: "MarchofEmpires", title: "March of Empires", description: "Strategy game from Gameloft", group: "gaming", recommended: true, icon: "favicon:gameloft.com" },
  { pattern: "NYTCrossword", title: "NYT Crossword", description: "New York Times crossword puzzle", group: "gaming", recommended: true, icon: "favicon:nytimes.com" },
  { pattern: "Royal Revolt", title: "Royal Revolt", description: "Tower defense / strategy game", group: "gaming", recommended: true, icon: "favicon:flaregames.com" },

  // Communication
  { pattern: "Microsoft.YourPhone", title: "Phone Link", description: "Smartphone companion", group: "communication", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.Messaging", title: "Messaging", description: "UWP messaging app (largely discontinued)", group: "communication", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.People", title: "People", description: "Contacts app", group: "communication", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.SkypeApp", title: "Skype", description: "Skype (UWP, discontinued)", group: "communication", recommended: true, icon: "skype" },
  { pattern: "Microsoft.WindowsCommunicationsApps", title: "Mail & Calendar", description: "Built-in Mail / Calendar", group: "communication", warning: "Removes both Mail and Calendar.", icon: "microsoft-outlook" },
  { pattern: "Microsoft.OutlookForWindows", title: "New Outlook", description: "Outlook web app wrapper", group: "communication", recommended: true, icon: "microsoft-outlook" },
  { pattern: "MicrosoftTeams", title: "Microsoft Teams (Old)", description: "Consumer Teams chat (legacy)", group: "communication", recommended: true, icon: "microsoft-teams" },
  { pattern: "MSTeams", title: "Microsoft Teams (New)", description: "New Teams app — actual package on Win11 24H2/25H2 is MSTeams_8wekyb3d8bbwe", group: "communication", recommended: true, icon: "microsoft-teams" },
  { pattern: "Microsoft.WindowsMeetNow", title: "Meet Now", description: "Skype Meet Now", group: "communication", recommended: true, icon: "skype" },
  { pattern: "*Facebook*", title: "Facebook", description: "Facebook social media app", group: "communication", recommended: true, icon: "facebook" },
  { pattern: "*Twitter*", title: "Twitter / X", description: "Twitter / X social app", group: "communication", recommended: true, icon: "x" },
  { pattern: "*Instagram*", title: "Instagram", description: "Instagram social app", group: "communication", recommended: true, icon: "instagram" },
  { pattern: "*LinkedIn*", title: "LinkedIn", description: "LinkedIn professional networking app", group: "communication", recommended: true, icon: "linkedin" },
  { pattern: "Viber", title: "Viber", description: "Messaging and calling app", group: "communication", recommended: true, icon: "viber" },
  { pattern: "XING", title: "XING", description: "Professional networking platform (DACH)", group: "communication", recommended: true, icon: "favicon:xing.com" },
  // Sponsored apps: Microsoft auto-pushes these via the Store after first network connect.
  // Specific publisher-prefixed names (Get-AppxPackage -AllUsers Name on real 25H2 installs).
  { pattern: "*WhatsApp*", title: "WhatsApp Desktop", description: "Sponsored app — Microsoft pushes via Store automatically", group: "communication", recommended: true, icon: "whatsapp" },
  { pattern: "5319275A.WhatsAppDesktop", title: "WhatsApp Desktop (publisher-prefixed)", description: "Explicit WhatsApp publisher namespace", group: "communication", recommended: true, icon: "whatsapp" },
  { pattern: "Facebook.Facebook", title: "Facebook", description: "Facebook app, sponsored installation", group: "communication", recommended: true, icon: "facebook" },
  { pattern: "Facebook.InstagramBeta", title: "Instagram", description: "Instagram app, sponsored installation", group: "communication", recommended: true, icon: "instagram" },
  { pattern: "BytedancePte.Ltd.TikTok", title: "TikTok", description: "TikTok app, sponsored installation", group: "communication", recommended: true, icon: "tiktok" },
  { pattern: "7EE7776C.LinkedInforWindows", title: "LinkedIn", description: "LinkedIn app, sponsored installation", group: "communication", recommended: true, icon: "linkedin" },

  // Media & streaming
  { pattern: "Microsoft.WindowsSoundRecorder", title: "Sound Recorder", description: "Voice recorder app", group: "media", icon: "microsoft-windows" },
  { pattern: "Microsoft.ZuneMusic", title: "Media Player (Groove)", description: "Modern Media Player / Groove successor", group: "media", warning: "If you use this for local audio/video, keep it.", icon: "microsoft-windows" },
  { pattern: "Microsoft.ZuneVideo", title: "Films & TV", description: "Video player app", group: "media", recommended: true, icon: "microsoft-windows" },
  { pattern: "ClipChamp.Clipchamp", title: "Clipchamp", description: "Microsoft video editor", group: "media", recommended: true, icon: "favicon:clipchamp.com" },
  { pattern: "*Spotify*", title: "Spotify (wildcard)", description: "Pre-installed Spotify promo (any publisher prefix)", group: "media", recommended: true, icon: "spotify" },
  { pattern: "SpotifyAB.SpotifyMusic", title: "Spotify (publisher-prefixed)", description: "Explicit Spotify publisher namespace for current 25H2 builds", group: "media", recommended: true, icon: "spotify" },
  { pattern: "*Disney*", title: "Disney+ (wildcard)", description: "Disney+ promo app", group: "media", recommended: true, icon: "disney-plus" },
  { pattern: "Disney.37853FC22B2CE", title: "Disney+ (publisher-prefixed)", description: "Explicit Disney+ publisher namespace", group: "media", recommended: true, icon: "disney-plus" },
  { pattern: "*TikTok*", title: "TikTok (wildcard)", description: "TikTok app", group: "media", recommended: true, icon: "tiktok" },
  { pattern: "*Netflix*", title: "Netflix (wildcard)", description: "Netflix promo app", group: "media", recommended: true, icon: "netflix" },
  { pattern: "4DF9E0F8.Netflix", title: "Netflix (publisher-prefixed)", description: "Explicit Netflix publisher namespace", group: "media", recommended: true, icon: "netflix" },
  { pattern: "*Amazon*", title: "Amazon (Shopping & Prime Video)", description: "Amazon shopping app and Prime Video promo", group: "media", recommended: true, icon: "amazon" },
  { pattern: "HULULLC.HULUPLUS", title: "Hulu", description: "Hulu streaming service app", group: "media", recommended: true, icon: "hulu" },
  { pattern: "SlingTV", title: "Sling TV", description: "Live TV streaming service", group: "media", recommended: true, icon: "favicon:sling.com" },
  { pattern: "Plex", title: "Plex", description: "Media server and player app", group: "media", recommended: true, icon: "plex" },
  { pattern: "PandoraMediaInc", title: "Pandora", description: "Pandora music streaming app", group: "media", recommended: true, icon: "pandora" },
  { pattern: "iHeartRadio", title: "iHeartRadio", description: "Internet radio streaming app", group: "media", recommended: true, icon: "favicon:iheart.com" },
  { pattern: "TuneInRadio", title: "TuneIn Radio", description: "Internet radio streaming app", group: "media", recommended: true, icon: "favicon:tunein.com" },
  { pattern: "Shazam", title: "Shazam", description: "Music identification app", group: "media", recommended: true, icon: "shazam" },
  { pattern: "ACGMediaPlayer", title: "ACG Media Player", description: "Generic UWP media player", group: "media", recommended: true, icon: "favicon:microsoft.com" },
  { pattern: "AdobeSystemsIncorporated.AdobePhotoshopExpress", title: "Photoshop Express", description: "Basic photo editor from Adobe", group: "media", recommended: true, icon: "adobe-photoshop-express" },
  { pattern: "AutodeskSketchBook", title: "Autodesk SketchBook", description: "Digital drawing and sketching app", group: "media", recommended: true, icon: "favicon:autodesk.com" },
  { pattern: "PicsArt-PhotoStudio", title: "PicsArt", description: "Photo editing and creative app", group: "media", recommended: true, icon: "favicon:picsart.com" },
  { pattern: "PhototasticCollage", title: "Phototastic Collage", description: "Photo collage creation app", group: "media", recommended: true, icon: "favicon:microsoft.com" },
  { pattern: "PolarrPhotoEditorAcademicEdition", title: "Polarr Photo Editor", description: "Photo editing app (Academic Edition)", group: "media", recommended: true, icon: "favicon:polarr.com" },
  { pattern: "Flipboard", title: "Flipboard", description: "Magazine-style news aggregator", group: "media", recommended: true, icon: "favicon:flipboard.com" },

  // System & Microsoft
  { pattern: "Microsoft.WindowsFeedbackHub", title: "Feedback Hub", description: "Send feedback to Microsoft", group: "system", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.549981C3F5F10", title: "Cortana", description: "Cortana voice assistant", group: "system", warning: "Pairs with the 'Disable Cortana' tweak in Search.", icon: "microsoft-windows" },
  { pattern: "Microsoft.Copilot", title: "Copilot (app)", description: "Microsoft Copilot standalone app", group: "system", recommended: true, icon: "microsoft-copilot" },
  { pattern: "*Copilot*", title: "Copilot (wildcard catch-all)", description: "Catches Microsoft.Copilot_*, Microsoft.Windows.Copilot etc. across Win11 24H2/25H2 renamings", group: "system", recommended: true, icon: "microsoft-copilot" },
  { pattern: "Microsoft.Windows.AIHub", title: "Copilot+ AI Hub", description: "Copilot+ AI Hub (Windows 11 24H2+)", group: "system", recommended: true, icon: "microsoft-copilot" },
  { pattern: "MicrosoftWindows.Client.AIX", title: "Windows AI Experience", description: "Copilot+ AI Experience component (25H2)", group: "system", recommended: true, icon: "microsoft-copilot" },
  { pattern: "Microsoft.MicrosoftEdge.Stable", title: "Microsoft Edge", description: "Edge browser", group: "system", warning: "Edge is treated as a mandatory Windows component — it may reinstall.", icon: "microsoft-edge" },
  { pattern: "MicrosoftCorporationII.QuickAssist", title: "Quick Assist", description: "Remote assistance tool", group: "system", icon: "microsoft-windows" },
  { pattern: "Microsoft.RemoteDesktop", title: "Remote Desktop", description: "Remote Desktop client app", group: "system", icon: "microsoft-windows" },
  { pattern: "Microsoft.WindowsFamilySafety", title: "Family Safety (UWP)", description: "Family Safety UWP component", group: "system", icon: "microsoft-windows" },
  { pattern: "MicrosoftCorporationII.MicrosoftFamily", title: "Family Safety App", description: "Family Safety hub for managing family accounts", group: "system", icon: "microsoft-windows" },
  { pattern: "Microsoft.PCManager", title: "Microsoft PC Manager", description: "MS system cleanup / optimization tool", group: "system", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.Windows.DevHome", title: "Dev Home", description: "Developer dashboard (discontinued)", group: "system", recommended: true, icon: "microsoft-windows" },
  { pattern: "Microsoft.NetworkSpeedTest", title: "Network Speed Test", description: "Internet connection speed test", group: "system", recommended: true, icon: "microsoft-windows" },
  { pattern: "MicrosoftWindows.CrossDevice", title: "Cross Device Experience", description: "Phone integration in File Explorer / Camera", group: "system", icon: "microsoft-windows" },
  { pattern: "MicrosoftWindows.Client.WebExperience", title: "Windows Web Experience Pack", description: "Backs Widgets and Web-driven Start features", group: "system", warning: "Disables Widgets and may affect Start.", icon: "microsoft-windows" },
  { pattern: "Microsoft.WidgetsPlatformRuntime", title: "Widgets Platform Runtime", description: "Runtime required for Windows Widgets", group: "system", warning: "Disables Widgets.", icon: "microsoft-windows" },
  { pattern: "Microsoft.StartExperiencesApp", title: "Widgets Experience", description: "Powers the Widgets My Feed surface", group: "system", recommended: true, icon: "microsoft-windows" },
  // Optional / risky utilities — opt-in only
  { pattern: "Microsoft.WindowsStore", title: "Microsoft Store", description: "Microsoft Store", group: "system", warning: "Cannot be reinstalled easily once removed.", icon: "microsoft-store" },
  { pattern: "Microsoft.WindowsTerminal", title: "Windows Terminal", description: "Default terminal app (PowerShell, CMD, WSL)", group: "system", warning: "Removing leaves you without a modern terminal.", icon: "windows-terminal" },
  { pattern: "Microsoft.WindowsCalculator", title: "Calculator", description: "Built-in calculator app", group: "system", warning: "Useful default utility — only remove if you have a replacement.", icon: "microsoft-windows" },
  { pattern: "Microsoft.WindowsNotepad", title: "Notepad", description: "Notepad text editor", group: "system", warning: "Useful default utility — only remove if you have a replacement.", icon: "microsoft-windows" },
  { pattern: "Microsoft.WindowsCamera", title: "Camera", description: "Built-in camera app", group: "system", warning: "Required for webcam usage in many UWP apps.", icon: "microsoft-windows" },
  { pattern: "Microsoft.Windows.Photos", title: "Photos", description: "Default photo viewer", group: "system", warning: "Default image viewer — only remove if you have a replacement.", icon: "microsoft-windows" },
  { pattern: "Microsoft.ScreenSketch", title: "Snipping Tool", description: "Screenshot and annotation tool", group: "system", warning: "Removes Win+Shift+S screenshot shortcut.", icon: "microsoft-windows" },
  { pattern: "Microsoft.Paint", title: "Paint", description: "Classic 2D paint application", group: "system", icon: "microsoft-windows" },
  { pattern: "Microsoft.MSPaint", title: "Paint 3D", description: "Paint 3D (modern paint app)", group: "system", recommended: true, icon: "microsoft-windows" },

  // Other / misc third-party
  { pattern: "Duolingo-LearnLanguagesforFree", title: "Duolingo", description: "Language learning app", group: "other", recommended: true, icon: "duolingo" },
  { pattern: "fitbit", title: "Fitbit", description: "Fitbit activity tracker companion app", group: "other", recommended: true, icon: "fitbit" },
  { pattern: "WinZipUniversal", title: "WinZip (UWP)", description: "File compression utility (UWP version)", group: "other", recommended: true, icon: "favicon:winzip.com" },
  { pattern: "Sidia.LiveWallpaper", title: "Live Wallpaper", description: "Live wallpaper app", group: "other", recommended: true, icon: "favicon:microsoft.com" },
  { pattern: "EclipseManager", title: "Eclipse Manager", description: "OEM display/utility helper", group: "other", recommended: true, icon: "favicon:microsoft.com" },
  { pattern: "ActiproSoftwareLLC", title: "Actipro Software", description: "UI controls/components bundled by some OEMs", group: "other", recommended: true, icon: "favicon:actiprosoftware.com" },
  { pattern: "CyberLinkMediaSuiteEssentials", title: "CyberLink Media Suite", description: "Multimedia software suite (OEM)", group: "other", recommended: true, icon: "favicon:cyberlink.com" },

  // OEM bloat (HP / Lenovo / Dell)
  { pattern: "AD2F1837.HPAIExperienceCenter", title: "HP AI Experience Center", description: "HP AI features hub", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPConnectedMusic", title: "HP Connected Music", description: "HP music service (discontinued)", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPConnectedPhotopoweredbySnapfish", title: "HP Connected Photo", description: "HP photo service via Snapfish (discontinued)", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPDesktopSupportUtilities", title: "HP Desktop Support Utilities", description: "HP desktop support tooling", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPEasyClean", title: "HP Easy Clean", description: "HP system cleaning utility", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPFileViewer", title: "HP File Viewer", description: "HP file viewer for specific formats", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPJumpStarts", title: "HP JumpStarts", description: "HP tutorials and quick-access app", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPPCHardwareDiagnosticsWindows", title: "HP PC Hardware Diagnostics", description: "HP hardware diagnostics", group: "oem", warning: "Useful for HP warranty support.", icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPPowerManager", title: "HP Power Manager", description: "HP battery / power management", group: "oem", warning: "On laptops this manages battery thresholds.", icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPPrinterControl", title: "HP Printer Control", description: "HP printer management app", group: "oem", icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPPrivacySettings", title: "HP Privacy Settings", description: "HP privacy controls", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPQuickDrop", title: "HP QuickDrop", description: "HP file-transfer-to-phone app", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPQuickTouch", title: "HP QuickTouch", description: "HP touch shortcut utility", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPRegistration", title: "HP Registration", description: "HP product registration", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPSupportAssistant", title: "HP Support Assistant", description: "HP support / update tool", group: "oem", warning: "Provides HP driver updates.", icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPSureShieldAI", title: "HP Sure Shield AI", description: "HP security software", group: "oem", icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPSystemInformation", title: "HP System Information", description: "HP system info display", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPWelcome", title: "HP Welcome", description: "HP welcome / first-run experience", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.HPWorkWell", title: "HP WorkWell", description: "HP wellness / break reminders", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "AD2F1837.myHP", title: "myHP", description: "HP central hub for device info & services", group: "oem", recommended: true, icon: "favicon:hp.com" },
  { pattern: "E046963F.LenovoCompanion", title: "Lenovo Vantage", description: "Lenovo OEM hub for settings / updates / support", group: "oem", warning: "Provides Lenovo driver updates and battery settings.", icon: "favicon:lenovo.com" },
  { pattern: "LenovoCompanyLimited.LenovoVantageService", title: "Lenovo Vantage Service", description: "Background service for Lenovo Vantage", group: "oem", icon: "favicon:lenovo.com" },
  { pattern: "DellInc.DellSupportAssistforPCs", title: "Dell SupportAssist", description: "Dell support / diagnostic / update tool", group: "oem", warning: "Provides Dell driver updates.", icon: "favicon:dell.com" },
  { pattern: "DellInc.DellDigitalDelivery", title: "Dell Digital Delivery", description: "Dell pre-purchased software delivery", group: "oem", recommended: true, icon: "favicon:dell.com" },
  { pattern: "DellInc.DellMobileConnect", title: "Dell Mobile Connect", description: "Dell phone-to-PC link (superseded by Phone Link)", group: "oem", recommended: true, icon: "favicon:dell.com" },
];

export const GROUP_LABELS: Record<BloatwareEntry["group"], string> = {
  consumer: "Consumer apps",
  office: "Office & productivity",
  gaming: "Gaming & Xbox",
  communication: "Communication",
  media: "Media & streaming",
  system: "System & Microsoft",
  oem: "OEM bloat (HP / Lenovo / Dell)",
  other: "Other",
};
